name: Feature Branch Test

on:
  push:
    branches:
      # Runs on any branch that's not main or develop
      - '**'
      - '!main'
    paths:
      # Only trigger when Python files or common config files change
      - '**/*.py'
      - 'pyproject.toml'
      - 'setup.py'
      - 'setup.cfg'
      - 'requirements*.txt'
      - '.flake8'
      - 'pytest.ini'
      - 'conftest.py'

jobs:
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-3.11-pip-${{ hashFiles('**/setup.cfg', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-3.11-pip-
        
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
        
    - name: Install dependencies
      run: |
        uv pip install --system pytest pytest-cov
        uv pip install --system -e ".[dev]"
          
    - name: Run pytest
      run: |
        pytest -v